version: "3.9"
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sql-server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "nicePass1"
      ACCEPT_EULA: "Y"