# Generated by Django 3.2.4 on 2021-06-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210609_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('self', 'Pickup'), ('delivery', 'Delivery')], default='self', max_length=100, verbose_name='Order type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'Order is complated'), ('is_ready', 'Order is ready'), ('in_progress', 'Order in progress'), ('new', 'New order')], default='new', max_length=100, verbose_name='Order status'),
        ),
    ]
