# Generated by Django 3.2.4 on 2021-06-10 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20210610_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('is_ready', 'Order is ready'), ('new', 'New order'), ('completed', 'Order is complated'), ('in_progress', 'Order in progress')], default='new', max_length=100, verbose_name='Order status'),
        ),
    ]
