# Generated by Django 3.2.4 on 2021-06-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20210610_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('is_ready', 'Order is ready'), ('completed', 'Order is complated'), ('in_progress', 'Order in progress'), ('new', 'New order')], default='new', max_length=100, verbose_name='Order status'),
        ),
    ]
