# Generated by Django 3.2.4 on 2021-06-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20210610_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('is_ready', 'Order is ready'), ('in_progress', 'Order in progress'), ('completed', 'Order is complated'), ('new', 'New order')], default='new', max_length=100, verbose_name='Order status'),
        ),
    ]
