# Generated by Django 3.2.4 on 2021-06-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_alter_order_buying_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Order in progress'), ('is_ready', 'Order is ready'), ('new', 'New order'), ('completed', 'Order is complated')], default='new', max_length=100, verbose_name='Order status'),
        ),
    ]
