# Generated by Django 3.2.4 on 2021-06-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'Order is complated'), ('in_progress', 'Order in progress'), ('new', 'New order'), ('is_ready', 'Order is ready')], default='new', max_length=100, verbose_name='Order status'),
        ),
    ]
