USE BSUIR_TERM_5
GO


SELECT *
FROM GROUPS;


SELECT *
FROM STUDENTS;

SELECT *
FROM LESSONS;

SELECT STUDY_ID, VAL, DATE, STUDENT_ID, IS_ABSENT, PREPODS_ID
FROM RATING
WHERE STUDY_ID = 'Python_Lab'
UNION
SELECT STUDY_ID, VAL, DATE, STUDENT_ID, IS_ABSENT, PREPODS_ID
FROM RATING
WHERE STUDY_ID = 'Python_LK'
UNION
SELECT STUDY_ID, VAL, DATE, STUDENT_ID, IS_ABSENT, PREPODS_ID
FROM RATING
WHERE STUDY_ID = 'DS_ML_LK'
UNION
SELECT STUDY_ID, VAL, DATE, STUDENT_ID, IS_ABSENT, PREPODS_ID
FROM RATING
WHERE STUDY_ID = 'DS_ML_Practice'
UNION
SELECT STUDY_ID, VAL, DATE, STUDENT_ID, IS_ABSENT, PREPODS_ID
FROM RATING
WHERE STUDY_ID = 'DS_ML_Lab'
ORDER BY STUDY_ID ASC;