version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    image: kremenevskiy/e-shop-image:2
    command: bash -c "
      chmod +x ./wait_db.sh
      ./wait_db.sh &&
      python ./shop/manage.py makemigrations &&
      python ./shop/manage.py migrate &&
      python ./shop/manage.py loaddata ./shop/dbsaved/datadump.json &&
      python ./shop/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
